on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
  
jobs:
  linter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5.x' ]

    steps:
      - uses: actions/checkout@v1

      - name: Rubocop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rspec:
    needs: linter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5.x' ]
    steps:
      - run: echo 'rspec!'

  e2e_survey:
    needs: linter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10' ]
    steps:
      - run: echo 'e2e_survey!'

  e2e_dashboard:
    needs: linter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10' ]
    steps:
      - run: echo 'e2e_dashboard!'

  build:
    needs: [rspec, e2e_survey, e2e_dashboard]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy!'

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy!'
