on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
  
jobs:
  linter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5.x' ]

    steps:
      - uses: actions/checkout@v1

      - name: Rubocop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby version
        uses: actions/setup-ruby@master
        with:
          ruby-version : ${{ matrix.ruby }}

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev

      - name: Set up bundler
        run: gem install bundler

      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundle install
        run: bundle install --path vendor/bundle

      - name: Rubocop checks
        run: bundle exec rubocop --parallel

  rspec:
    needs: linter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5.x' ]
    steps:
      - run: echo 'rspec!'

  build:
    needs: [rspec, e2e_survey, e2e_dashboard]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy!'

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy!'
